### ISSUE TITLE
Allow for `tags` (& maybe `documentation`) on Triggers, similar to Pipelines.

### ISSUE THREAD

**Issue by graza-io** [turbot/pipe-fittings#395] opened 2024-04-26 15:20 UTC
## Context

Currently we have the ability to add the following to `pipelines`:
- Title
- Description
- Documentation
- Tags

It would be beneficial to be able to at least `tag` our `triggers` also, however it seems of the above, `triggers` only support:
- Title
- Description

There may also be benefits to adding `documentation` to `triggers` is this can be viewed on the `hub`.

**Comment by vhadianto** [comment] 2024-05-10 08:31
@graza-io Triggers do support Title, Description, Documentation & Tags.

I think we can close this issue? What's failing is the ability to use `expression` in these common attributes.

**Comment by graza-io** [comment] 2024-05-10 08:49
I think that:
- `Documentation` should allow use of `file()` to render markdown, especially for the Hub.
- `Tags` should allow use of `merge()` to define some common tags and those specific for that instance.

**Comment by vhadianto** [comment] 2024-05-10 13:26
Dupe of https://github.com/turbot/pipe-fittings/issues/394

**Closed by vhadianto** 2024-05-10 13:26 UTC
Labels: enhancement
